# Generated by Django 2.2.7 on 2019-11-27 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DATASET_NLP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.IntegerField(max_length=11)),
                ('question', models.CharField(max_length=3000)),
                ('question_intent', models.CharField(max_length=3000)),
                ('question_ner', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='DATASET_ANSWER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=3000)),
                ('answer_intent', models.CharField(max_length=3000)),
                ('answer_ner', models.CharField(max_length=200)),
                ('conversation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blackboard.DATASET_NLP')),
            ],
        ),
    ]
