# Generated by Django 2.2.7 on 2019-12-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackboard', '0003_remove_dataset_answer_conversation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset_answer',
            name='conversation_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataset_nlp',
            name='conversation_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
