# Generated by Django 2.2.7 on 2020-01-29 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blackboard', '0005_dataset_answer_question_ner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset_answer',
            old_name='question_ner',
            new_name='quest_ner',
        ),
    ]
